sutpc:
  sys:
    log:
      #系统日志接口调用----域名(IP):端口号(结尾要记得带 / )
      path: http://127.0.0.1:9051/sysmanager/
  #组合报告
  statement:
    #扫描handler的包名
    handler-scan-package: com.sutpc.its.statement
spring:
  application:
    name: spb-StandardizedIndex

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: dev
  datasource:
    name: common-test
    # 深圳指数测试库
    #四期
    #url: jdbc:oracle:thin:@10.3.4.72:1521:tpmodel
    #五期
    url: jdbc:oracle:thin:@10.10.180.65:1522:tpmodel
    username: sa
    password: Tpi_332506
#    湛江的数据库 没有权限
#    url: jdbc:oracle:thin:@10.10.180.65:1522:tpmodel
#    username: sa
#    password: Sa123456
    #托管机房账号密码
    #username: sa
    #password: b29iGV6iSp3dj0B
#    福田新指数系统
#    url: jdbc:oracle:thin:@172.0.7.110:1521:tpmodel
#    username: sa
#    password: Sa123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#预警邮件配置信息.
mail:
  host: smtp.exmail.qq.com
  acct: lizhongqiao@sutpc.com
  password: bshBUKdtoZ64PrSx
  from: 深圳指数系统<lizhongqiao@sutpc.com>
  #from: 深圳指数系统（五/六期）<1016197893@qq.com>
server:
  port: 8085
  session:
    timeout: 30

# sql日志输出
logging:
  level:
    com.sutpc.its.dao: debug

appUrl:
  isRunnable : false

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  # MapperXml中实体类别名
  type-aliases-package: com.sutpc.its.model


