spring:
  application:
    name: SzCustomization

  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  profiles:
    active: dev
  datasource:
    name: common-test
    # 同济库库
    url: jdbc:oracle:thin:@10.10.2.107:10107:ORCL
    username: sa
    password: Sa332506
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    
server:
  port: 8087
  session:
    timeout: 30
 
# sql日志输出
logging:
    level:
      com.sutpc.its.dao: DEBUG
    
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  # MapperXml中实体类别名
  type-aliases-package: com.sutpc.its.model
